# Generated by Django 5.2.1 on 2025-06-04 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id_coordenada', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.IntegerField()),
                ('hora_final', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id_parada', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('id_parada_puma', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta_puma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sentido', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_id', models.ForeignKey(db_column='dia_id', on_delete=django.db.models.deletion.CASCADE, to='api.dia')),
                ('id_horar', models.ForeignKey(db_column='id_horar', on_delete=django.db.models.deletion.CASCADE, to='api.horario')),
            ],
            options={
                'db_table': 'dia_horario',
                'unique_together': {('id_horar', 'dia_id')},
            },
        ),
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('id_coordenada', models.ForeignKey(db_column='id_coordenada', on_delete=django.db.models.deletion.CASCADE, to='api.coordenada')),
                ('parada', models.ForeignKey(db_column='id_parada', on_delete=django.db.models.deletion.CASCADE, to='api.parada')),
                ('ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, to='api.ruta')),
            ],
            options={
                'db_table': 'paradaruta',
                'unique_together': {('ruta', 'parada')},
            },
        ),
        migrations.CreateModel(
            name='RutaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_id_horario', models.ForeignKey(db_column='horario_id_horario', on_delete=django.db.models.deletion.CASCADE, to='api.horario')),
                ('rutas_id_ruta_puma', models.ForeignKey(db_column='rutas_id_ruta_puma', on_delete=django.db.models.deletion.CASCADE, to='api.ruta')),
            ],
            options={
                'db_table': 'ruta_horario',
                'unique_together': {('rutas_id_ruta_puma', 'horario_id_horario')},
            },
        ),
    ]
