# Generated by Django 5.2.1 on 2025-06-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_coordenada_created_at_coordenada_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("informacion", models.TextField()),
                (
                    "paradas_afectadas",
                    models.ManyToManyField(
                        related_name="notificaciones", to="api.parada"
                    ),
                ),
                (
                    "ruta_afectada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_afectada",
                        to="api.ruta",
                    ),
                ),
                (
                    "ruta_auxiliar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_auxiliar",
                        to="api.ruta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
