# Generated by Django 5.2.1 on 2025-06-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_coordenada_created_at_coordenada_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="horario",
            name="dias",
            field=models.ManyToManyField(
                related_name="horarios",
                through="api.DiaHorario",
                through_fields=("id_horar", "dia_id"),
                to="api.dia",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="horarios",
            field=models.ManyToManyField(
                related_name="rutas",
                through="api.RutaHorario",
                through_fields=("rutas_id_ruta_puma", "horario_id_horario"),
                to="api.horario",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="paradas",
            field=models.ManyToManyField(
                related_name="rutas",
                through="api.ParadaRuta",
                through_fields=("ruta", "parada"),
                to="api.parada",
            ),
        ),
    ]
